### PR TITLE
Fix error handling, exception printing, JSON serialization and build failing

### PR DESCRIPTION
**Pull request by bezda**

### CODE REVIEW

**Comment by isparkes** [comment]
I don't really agree with your change to add "proper" serialization, it was a conscious decision not to manage serialization objects for the entirely static JSON. If you can make a case for doing this, other than "personal taste", then we can talk about it.

I'm not wild about adding the "net.sf.json" imports either, we're using Jackson for the deserialization, aren't we just making a zoo if we add another JSON dependency?

If we *do* go down this path, we should improve the Exception handling.

The other things look like good improvements.

**Comment by bezda** [comment]
Hi Ian,
I've added the JSON serialization because my jobs need to put JSON string into JIRA field. It seems silly to have a build step which escapes the original JSON to use as value for this field. 
I agree that importing 'net.sf' is a bit messy, but I wasn't sure which serializer to use and this one was already on classpath. I can create proper JSON objects and use ObjectMapper to serialize it if you agree

**Comment by jbaiza** [comment]
In merge request " Escape json #14" I already added json escaping. It just waits in line with other merge requests.

**Comment by isparkes** [comment]
I personally prefer jbaiza's solution to the JSON escaping, I think it makes it more explicit what the aim is.

@jbaiza  @bezda  Unfortunately, I don't either have write rights to the repository. @laszlomiklosik seems to have not been around for some time...

**Comment by bezda** [comment]
Ok, I've removed the serialization from this PR. Would be great if someone could get write permissions and merge

**Comment by isparkes** [comment]
I'm working on it...

**Comment by laszlomiklosik** [comment]
Hi all, sorry for the late response. If you fix the merge conflicts we can merge this PR. I personally like serialization, but would not add net.sf.json for that, rather use whatever JSON libary from the classpath (jackson I think). Cheers, Laszlo

**Comment by bezda** [comment]
I've fixed the merge  conflict, this should be good to go.
The net.sf.json was from classpath - it's one of core Jenkins libraries. I can create proper objects and serialize them using ObjectMapper, but if you're going to merge https://github.com/jenkinsci/jira-issue-updater-plugin/pull/14 then there's no point...

**Comment by bezda** [comment]
Ok, rebased again :)

**Comment by isparkes** [comment]
Looks good!

**Pull request merged**
