### PR TITLE
Update transition api payload

### PR DESCRIPTION
**Pull request by bezda**
This change is compatible from JIRA 5.0 up - https://docs.atlassian.com/jira/REST/5.0/#id199973

### CODE REVIEW

**Comment by bezda** [comment]
This change is compatible up to JIRA 5.0

**Comment by bezda** [comment]
Hey, any update on this PR?

**Comment by bezda** [comment]
Also new release would be nice :)

**Comment by isparkes** [comment]
Thanks for prodding me. I'll have to have a look at it a bit later today, right in the middle of something now.

**Comment by bezda** [comment]
I can only test with jira 7, but according to documentation it should work with jira 5+

**Pull request merged**
